#!/usr/bin/env php
<?php
/**
 * Script for syncing changes to the vanilla/vanilla repositoriy.
 *
 * @author Adam Charron <adam.c@vanillaforums.com>
 * @copyright 2009-2020 Vanilla Forums Inc.
 * @license Proprietary
 */

namespace Vanilla\Cloud\Scripts;

$script = new OssSyncScript();

register_shutdown_function([$script, 'cleanup']);

$script->run();
