<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Preferences']['Email']['Groups'] = '1';
$Configuration['Preferences']['Popup']['Groups'] = '1';

$Configuration['Preferences']['Email']['Events'] = '1';
$Configuration['Preferences']['Popup']['Events'] = '1';