before_install:
# Ensure a consistent yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

addons: 
  chrome: stable

# Install Vanilla and make symlinks
install:
  - ./travis/install.sh

# Cache Composer package files.
cache:
  directories:
    - $HOME/.composer/cache/files
    - $TRAVIS_BUILD_DIR/vanilla/node_modules
  yarn: true

# The project's primary programming language. This will affect default dependency availability.
language: php

# Configure the build.
matrix:
  fast_finish: true

# The versions of PHP to test the project under.
php:
  - 7.2
  - 7.1
  - 7.0

# Steps of the build script.
script:
  - cd vanilla
  - ./vendor/bin/phpunit --exclude-group=large
  - ./vendor/bin/phpcs --standard=./vendor/vanilla/standards/code-sniffer/Vanilla -p  ./plugins/knowledge/**/*.php
  - yarn build

env:
  - TEST_FILE_ROOTS = (plugins/knowledge)

# Run build in a Docker container.  Reduces time between commit and start of build.
sudo: false
