# Configure the build.
jobs:
  fast_finish: true
  include:
    # PHP 7.2 Job. This should always run.
    - name: PHP 7.2
      language: php
      php: 7.2
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      before_script:
        - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
        - ./travis/install.sh
        - cd vanilla
        - composer self-update
        - composer install --optimize-autoloader
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
          - ./vendor/bin/phpunit --exclude-group=large
  # Frontend JS Job
    - name: JS Build & Test
      language: node_js
      node_js: 10.9
      addons:
        chrome: stable
      env:
        - TEST_FILE_ROOTS=()
      before_script:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4 # Ensure a consistent yarn version
        - export PATH=$HOME/.yarn/bin:$PATH
        - ./travis/install.sh
        - cd vanilla
        - yarn install --pure-lockfile
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/vanilla/node_modules
        yarn: true
      script:
        - yarn build -i
        - yarn test

# No additional system dependencies to install. Skip the install step.
install: true

# Run build in a Docker container.  Reduces time between commit and start of build.
sudo: false
