# Configure the build.
dist: xenial
jobs:
  fast_finish: true
  include:
    # PHP 7.2 Job. This should always run.
    - name: PHP 7.2
      language: php
      php: 7.2
      services:
      - mysql
      addons:
        apt:
          packages:
            - nginx
            - realpath
        hosts:
          - vanilla.test
      before_script:
        - cd vanilla
        - composer self-update
        - composer install --optimize-autoloader
      cache:
        directories:
          - $HOME/.composer/cache/files
      script:
          - ./vendor/bin/phpunit --exclude-group=large
      env:
        - VANILLA_BUILD_DISABLE_AUTO_BUILD=true
  # Frontend JS Job
    - name: JS Build & Test
      language: node_js
      node_js: 10.9
      addons:
        chrome: stable
      env:
        - TEST_FILE_ROOTS=()
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/vanilla/node_modules
        yarn: true
      script:
        - yarn build -i
        - yarn test

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4 # Ensure a consistent yarn version
  - export PATH=$HOME/.yarn/bin:$PATH
  - phpenv config-rm xdebug.ini # Remove xdebug for better performance.
  - ./travis/install.sh
  - cd vanilla
  - yarn install --pure-lockfile
# No additional system dependencies to install. Skip the install step.
install: true
notifications:
  slack:
    secure: HX5bvTXP7/71hvUleIXYNN9TN4eWABrG9NszIlLwGhX50HqLesXBfRubtD06bOwu1h34vi+20MXKhE3Sf6S/tyh5XWsDXtjdeUZToOWkmCD9eOrDrt5pKqE9GS445BVmpPo5i5cQ//u+MJXPC507F8ZF7W9TZH/WTkvVOHz++wQ=
