<?php return array (
  'name' => 'Twitter Emoji',
  'description' => 'The emoji used on Twitter\'s web app. Twitter emoji for everyone.',
  'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" height="18" />',
  'emoji' => 
  array (
    -1 => '-1.png',
    '+1' => '+1.png',
    'angry' => 'angry.png',
    'anguished' => 'anguished.png',
    'astonished' => 'astonished.png',
    'bawling' => 'bawling.png',
    'bleep_bloop' => 'bleep_bloop.png',
    'blush' => 'blush.png',
    'cold_sweat' => 'cold_sweat.png',
    'confounded' => 'confounded.png',
    'confused' => 'confused.png',
    'cookie' => 'cookie.png',
    'cry' => 'cry.png',
    'dissapointed' => 'dissapointed.png',
    'dissapointed_relieved' => 'dissapointed_relieved.png',
    'dizzy' => 'dizzy.png',
    'expressionless' => 'expressionless.png',
    'fearful' => 'fearful.png',
    'flushed' => 'flushed.png',
    'frown' => 'frown.png',
    'grey_question' => 'grey_question.png',
    'grimace' => 'grimace.png',
    'grin' => 'grin.png',
    'heart' => 'heart.png',
    'heartbreak' => 'heartbreak.png',
    'hushed' => 'hushed.png',
    'innocent' => 'innocent.png',
    'joy' => 'joy.png',
    'kiss' => 'kiss.png',
    'kissing_blush' => 'kissing_blush.png',
    'kissing_closed_eyes copy' => 'kissing_closed_eyes copy.png',
    'kissing_smiling_eyes' => 'kissing_smiling_eyes.png',
    'kissing_wink' => 'kissing_wink.png',
    'lol' => 'lol.png',
    'love' => 'love.png',
    'mask' => 'mask.png',
    'mrgreen' => 'mrgreen.png',
    'naughty' => 'naughty.png',
    'neutral' => 'neutral.png',
    'no_mouth' => 'no_mouth.png',
    'open_mouth' => 'open_mouth.png',
    'pensive' => 'pensive.png',
    'persevere' => 'persevere.png',
    'rage' => 'rage.png',
    'relaxed' => 'relaxed.png',
    'relieved' => 'relieved.png',
    'scream' => 'scream.png',
    'sleeping' => 'sleeping.png',
    'sleepy' => 'sleepy.png',
    'smile' => 'smile.png',
    'smiley' => 'smiley.png',
    'smirk' => 'smirk.png',
    'star' => 'star.png',
    'stuck_out_tongue_closed_eyes' => 'stuck_out_tongue_closed_eyes.png',
    'stuck_out_tongue_winking_eye' => 'stuck_out_tongue_winking_eye.png',
    'sunglasses' => 'sunglasses.png',
    'sweat' => 'sweat.png',
    'sweat_smile' => 'sweat_smile.png',
    'tired_face' => 'tired_face.png',
    'tongue' => 'tongue.png',
    'triumph' => 'triumph.png',
    'trollface' => 'trollface.png',
    'unamused' => 'unamused.png',
    'warning' => 'warning.png',
    'weary' => 'weary.png',
    'wink' => 'wink.png',
    'worried' => 'worried.png',
    'yum' => 'yum.png',
  ),
  'aliases' => 
  array (
    ':)' => 'smile',
    ':D' => 'grin',
    ':(' => 'frown',
    ';)' => 'wink',
    ':\\' => 'confused',
    ':/' => 'confused',
    ':o' => 'open_mouth',
    ':s' => 'confounded',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    ':|' => 'neutral',
    'D:' => 'anguished',
    'B)' => 'sunglasses',
    ':#' => 'grimace',
    'o:)' => 'innocent',
    '<3' => 'heart',
    '(*)' => 'star',
    '=)' => 'smiley',
    '>_<' => 'rage',
  ),
  'editor' => 
  array (
    ':)' => 'smile',
    ':D' => 'smiley',
    ';)' => 'wink',
    ':\\' => 'confused',
    ':o' => 'open_mouth',
    ':s' => 'confounded',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    'B)' => 'sunglasses',
    ':#' => 'grin',
    'o:)' => 'innocent',
    '<3' => 'heart',
  ),
  'minSize' => 
  array (
    'w' => 34,
    'h' => 34,
  ),
  'maxSize' => 
  array (
    'w' => 40,
    'h' => 40,
  ),
  'sizes' => 
  array (
    0 => 1,
  ),
  'author' => 'Twitter, Inc.',
);
