<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Preferences']['Email']['Badge']   = '1';
$Configuration['Preferences']['Popup']['Badge']   = '1';