<?php return array (
  'name' => 'Little Emoji',
  'author' => 'Todd Burry',
  'description' => 'Inspired by the the original 15px smileys seen on forums everywhere, but updated with a modern twist.',
  'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" srcset="{dir}/{basename}@2x{ext} 2x" />',
  'emoji' =>
  array (
    '-1' => '-1.png',
    '+1' => '+1.png',
    'angry' => 'angry.png',
    'anguished' => 'anguished.png',
    'awesome' => 'awesome.png',
    'bawling' => 'bawling.png',
    'bleep_bloop' => 'bleep_bloop.png',
    'blush' => 'blush.png',
    'chuffed' => 'chuffed.png',
    'confounded' => 'confounded.png',
    'confused' => 'confused.png',
    'cry' => 'cry.png',
    'dizzy' => 'dizzy.png',
    'eh' => 'eh.png',
    'expressionless' => 'expressionless.png',
    'fearful' => 'fearful.png',
    'frown' => 'frown.png',
    'glasses' => 'glasses.png',
    'grin' => 'grin.png',
    'heart' => 'heart.png',
    'heartbreak' => 'heartbreak.png',
    'hurrah' => 'hurrah.png',
    'innocent' => 'innocent.png',
    'lol' => 'lol.png',
    'love' => 'love.png',
    'mrgreen' => 'mrgreen.png',
    'naughty' => 'naughty.png',
    'neutral' => 'neutral.png',
    'no_mouth' => 'no_mouth.png',
    'open_mouth' => 'open_mouth.png',
    'pleased' => 'pleased.png',
    'proud' => 'proud.png',
    'rage' => 'rage.png',
    'scream' => 'scream.png',
    'silenced' => 'silenced.png',
    'skull' => 'skull.png',
    'smile' => 'smile.png',
    'smiley' => 'smiley.png',
    'star' => 'star.png',
    'sunglasses' => 'sunglasses.png',
    'surprised' => 'surprised.png',
    'sweat' => 'sweat.png',
    'tongue' => 'tongue.png',
    'unamused' => 'unamused.png',
    'waving' => 'waving.png',
    'wink' => 'wink.png',
    'winky' => 'winky.png',
  ),
  'aliases' =>
  array (
    ':)' => 'smile',
    ':D' => 'grin',
    ':(' => 'frown',
    ';)' => 'wink',
    ':\\' => 'confused',
    ':/' => 'confused',
    ':o' => 'open_mouth',
    ':s' => 'confounded',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    ':|' => 'neutral',
    'D:' => 'anguished',
    'B)' => 'sunglasses',
    'o:)' => 'innocent',
    '<3' => 'heart',
    '(*)' => 'star',
    '>:)' => 'naughty',
    'o.O' => 'eh',
    '8-)' => 'glasses',
    '=)' => 'smiley',
    '>_<' => 'rage',
  ),
  'editor' =>
  array (
    ':)' => 'smile',
    ':D' => 'smiley',
    ';)' => 'wink',
    ':o' => 'open_mouth',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    'B)' => 'sunglasses',
    ':#' => 'grin',
    'o:)' => 'innocent',
    '<3' => 'heart',
    '(*)' => 'star',
    '>:)' => 'naughty',
  ),
  'minSize' =>
  array (
    'w' => 15,
    'h' => 18,
  ),
  'maxSize' =>
  array (
    'w' => 22,
    'h' => 18,
  ),
  'sizes' =>
  array (
    0 => 1,
    1 => 2,
  ),
);
