<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s en u';
$Definition['%s comment'] = '%s opmerking';
$Definition['%s comments'] = '%s opmerkingen';
$Definition['%s Connect'] = '%s verbinden';
$Definition['%s message'] = '%s bericht';
$Definition['%s New'] = '%s Nieuw';
$Definition['%s new'] = '%s nieuw';
$Definition['%s New Plural'] = '%s Nieuw';

$Definition['1 message'] = '1 bericht';

$Definition['About'] = 'Over';
$Definition['Accepted'] = 'Geaccepteerd';
$Definition['Activity'] = 'Activiteit';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s heeft profiel %6$s bijgewerkt.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s heeft profiel %6$s bijgewerkt.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s heeft opmerking geplaatst op %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s heeft u toegevoegd aan een %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s heeft u toegevoegd aan een %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s heeft een opmerking geplaatst op uw %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s heeft een opmerking geplaatst op uw %8$s.';
$Definition['Activity.Comment'] = 'Opmerking';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s heeft u een %8$s gestuurd.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s heeft u een %8$s gestuurd.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s heeft opmerking geplaatst op %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s heeft opmerking geplaatst op %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s heeft %3$s genoemd in een %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s heeft gegevens geimporteerd.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s heeft gegevens geimporteerd.';
$Definition['Activity.Join.FullHeadline'] = '%1$s neemt nu deel.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s neemt nu deel.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s heeft aanvraag lidmaatschap %4$s goedgekeurd.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s heeft aanvraag lidmaatschap %4$s goedgekeurd.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s heeft een account voor %1$s gemaakt.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s heeft een account voor %1$s gemaakt.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s heeft uitnodiging lidmaatschap %4$s geaccepteerd.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s heeft uitnodiging lidmaatschap %4$s geaccepteerd.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s is een %8$s begonnen.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s is een %8$s begonnen.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s heeft profielfoto %6$s gewijzigd.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s heeft profielfoto %6$s gewijzigd.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s heeft rechten %4$s gewijzigd.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s heeft rechten %4$s gewijzigd.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s aangemeld.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s aangemeld.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s schreef op %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s schreef:';
$Definition['Add'] = 'Toevoegen';
$Definition['Add Comment'] = 'Opmerking toevoegen';
$Definition['Add a Comment'] = 'Reactie toevoegen';
$Definition['Add Info &amp; Create Account'] = 'Info toevoegen &amp; Create Account';
$Definition['Add Message'] = 'Bericht toevoegen';
$Definition['Add People to this Conversation'] = 'Personen aan dit gesprek toevoegen';
$Definition['All Conversations'] = 'Alle gesprekken';
$Definition['All Discussions'] = 'Alle discussies';
$Definition['Allow other members to see your email?'] = 'Mogen andere leden uw e-mailadres zien?';
$Definition['Announce'] = 'Aankondigen';
$Definition['Applicants'] = 'Aanvragers';
$Definition['Apply'] = 'Aanvragen';
$Definition['Apply for Membership'] = 'Registreren';
$Definition['Are you sure you want to do that?'] = 'Weet u zeker dat u dit wilt doen?';
$Definition['at'] = 'om';

$Definition['Back to Discussions'] = 'Terug naar Discussies';
$Definition['Bookmark'] = 'Bladwijzer';
$Definition['bookmarked discussion'] = 'discussie met bladwijzer';
$Definition['Bookmarked Discussions'] = 'Discussies met bladwijzers';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Door een bestand te uploaden verklaart u het recht te hebben de foto te verspreiden en dat de foto niet strijdig is met de algemene voorwaarden.';

$Definition['Cancel'] = 'Annuleren';
$Definition['Categories'] = 'Categoriën';
$Definition['Category'] = 'Categorie';
$Definition['Change My Password'] = 'Mijn wachtwoord wijzigen';
$Definition['Change My Picture'] = 'Mijn foto wijzigen';
$Definition['Close'] = 'Sluiten';
$Definition['Closed'] = 'Gesloten';
$Definition['comment'] = 'opmerking';
$Definition['Comment'] = 'Opmerking';
$Definition['Confirm'] = 'Bevestigen';
$Definition['Confirm Password'] = 'Wachtwoord bevestigen';
$Definition['Connect'] = 'Verbinding maken';
$Definition['conversation'] = 'gesprek';
$Definition['Conversations'] = 'Gesprekken';
$Definition['Create One.'] = 'Een maken.';

$Definition['Dashboard'] = 'Dashboard';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Verwijderen';
$Definition['Delete Account'] = 'Account verwijderen';
$Definition['Delete Conversation'] = 'Gesprek verwijderen';
$Definition['Delete Discussion'] = 'Discussie verwijderen';
$Definition['discussion'] = 'discussie';
$Definition['Discussion Title'] = 'Discussietitel';
$Definition['Discussions'] = 'Discussies';
$Definition['Don\'t have an account? %s'] = 'Geen account? %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Door het vierkant hieronder te verslepen en van formaat te veranderen bepaalt u uw miniatuur.';

$Definition['Edit'] = 'Bewerken';
$Definition['Edit Account'] = 'Account bewerken';
$Definition['Edit My Account'] = 'Mijn account bewerken';
$Definition['Edit My Thumbnail'] = 'Mijn miniatuur bewerken';
$Definition['Edit Preferences'] = 'Voorkeuren bewerken';
$Definition['Email'] = 'E-mail';
$Definition['Email Notifications'] = 'E-mailmeldingen';
$Definition['Email Unavailable'] = 'E-mail niet beschikbaar';
$Definition['EmailInvitation'] = 'Hallo!

%1$s heeft u uitgenodigd om deel te nemen aan %2$s. Neem deel door op deze koppeling te klikken:

  %3$s

Bedankt!';
$Definition['EmailMembershipApproved'] = 'Beste %1$s,

Uw lidmaatschap is goedgekeurd. Meld u nu aan via deze koppeling:

  %2$s
  
Bedankt!';
$Definition['EmailNotification'] = '%1$s

Volg deze koppeling om het te proberen:
%2$s

Bedankt!';
$Definition['EmailPassword'] = 'Beste %1$s,

%2$s heeft uw wachtwoord voor %3$s gereset. Uw aanmeldgegevens zijn nu:

  E-mailadres: %6$s
  Wachtwoord: %5$s
  URL: %4$s

Bedankt!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Volg deze koppeling om het te proberen:
%2$s

Bedankt!';
$Definition['EmailWelcome'] = 'Beste %1$s,

%2$s heeft een account voor u gemaakt bij %3$s. Uw aanmeldgegevens zijn:

  E-mailadres: %6$s
  Wachtwoord: %5$s
  URL: %4$s

Bedankt!';
$Definition['EmailWelcomeConnect'] = 'Beste {User.Name},

U bent nu verbonden met {Title}. Dit zijn uw gegevens:

  Gebruikersnaam: {User.Name}
  Verbonden met: {ProviderName}

U kunt de site vinden op {/,url,domain}.

Bedankt!';
$Definition['EmailWelcomeRegister'] = 'Beste {User.Name},

U bent nu geregistreerd voor een account bij {Title}. Dit zijn uw gegevens:

  Gebruikersnaam: {User.Name}
  E-mailadres: {User.Email}

U kunt de site vinden op {/,url,domain}.

Bedankt!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Voer het e-mailadres in van de persoon die u wilt uitnodigen:';
$Definition['Enter your Email address'] = 'Voer uw e-mailadres in';
$Definition['Enter your existing account password.'] = 'Voer het huidige wachtwoord van uw account in.';
$Definition['ErrorCredentials'] = 'Er is geen account gevonden voor het ingevoerde e-mailadres en wachtwoord.';
$Definition['ErrorPermission'] = 'Geen toestemming.';
$Definition['ErrorRecordNotFound'] = 'De gevraagde gegevens zijn niet gevonden.';
$Definition['ErrorTermsOfService'] = 'U moet akkoord gaan met de algemene voorwaarden.';

$Definition['Female'] = 'Vrouw';
$Definition['Forgot?'] = 'Vergeten?';

$Definition['Gender'] = 'Man/vrouw';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'OK';
$Definition['GuestModule.Message'] = 'Nieuw hier? Klik op een van deze knoppen als u wilt meedoen!';

$Definition['he'] = 'hij';
$Definition['her'] = 'haar';
$Definition['his'] = 'zijn';
$Definition['Howdy, Stranger!'] = 'Hallo!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'Ik ga akkoord met de <a id="TermsOfService" class="Popup" target="terms" href="%s">algemene voorwaarden</a>';
$Definition['I remember now!'] = 'Ik weet het weer!';
$Definition['In this Conversation'] = 'In dit gesprek';
$Definition['Inbox'] = 'Postvak IN';
$Definition['Internal'] = 'Intern';
$Definition['Invitation Code'] = 'Uitnodigingscode';
$Definition['Invite'] = 'Uitnodigen';
$Definition['Invited by'] = 'Uitgenodigd door';

$Definition['Joined'] = 'Deelgenomen';

$Definition['Keep me signed in'] = 'Aangemeld blijven';

$Definition['Last Active'] = 'Laatste keer actief';
$Definition['Login with Facebook'] = 'Aanmelden met Facebook';

$Definition['Male'] = 'Man';
$Definition['Most recent by %1$s'] = 'Meest recent %1$s';
$Definition['My Bookmarks'] = 'Mijn bladwijzers';
$Definition['My Discussions'] = 'Mijn discussies';
$Definition['My Drafts'] = 'Mijn concepten';
$Definition['My Invitations'] = 'Mijn uitnodigingen';
$Definition['My Preferences'] = 'Mijn voorkeuren';

$Definition['Name Unavailable'] = 'Naam niet beschikbaar';
$Definition['No discussions were found.'] = 'Geen discussies gevonden.';
$Definition['Notifications'] = 'Meldingen';
$Definition['Notify me of private messages.'] = 'Melden wanneer ik een prive-bericht ontvang.';
$Definition['Notify me when I am added to private conversations.'] = 'Melden wanneer ik word toegevoegd aan een prive-gesprek.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Melden wanneer mensen een opmerking plaatsen bij mijn discussies met bladwijzer.';
$Definition['Notify me when people comment on my discussions.'] = 'Melden wanneer mensen een opmerking plaatsen bij mijn discussies.';
$Definition['Notify me when people mention me in comments.'] = 'Melden wanneer mensen mij noemen in een opmerking.';
$Definition['Notify me when people mention me in discussion titles.'] = 'Melden wanneer mensen mij noemen in een discussietitel.';
$Definition['Notify me when people reply to my wall comments.'] = 'Melden wanneer mensen antwoorden op opmerkingen op mijn virtuele muur.';
$Definition['Notify me when people write on my wall.'] = 'Melden wanneer mensen iets schrijven op mijn virtuele muur.';

$Definition['Okay'] = 'OK';
$Definition['On'] = 'Aan';
$Definition['Options'] = 'Opties';
$Definition['Or you can...'] = 'Wat ook kan...';
$Definition['Original'] = 'Oorspronkelijk';

$Definition['PageDetailsMessage'] = '%1$s aan %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s aan %2$s van %3$s';
$Definition['Password'] = 'Wachtwoord';
$Definition['PasswordRequest'] = 'Beste %1$s,

Iemand heeft gevraagd of u uw wachtwoord wilt resetten op %2$s. Volg deze koppeling om uw wachtwoord te resetten:

  %3$s

Als u hier zelf niet om hebt gevraagd, kunt u dit e-mailbericht negeren.';
$Definition['Passwords don\'t match'] = 'Wachtwoorden komen niet overeen';
$Definition['Permalink'] = 'Permanente koppeling';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">hier</a>.'] = 'U wordt doorgestuurd. Even geduld. Als u niet wordt doorgestuurd, klik dan <a href="%s">hier</a>.';
$Definition['Post Comment'] = 'Opmerking plaatsen';
$Definition['Post Discussion'] = 'Discussie plaatsen';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'Voorbeeld';
$Definition['Profile Picture'] = 'Profielfoto';

$Definition['Recent Activity'] = 'Recente activiteit';
$Definition['Recipients'] = 'Ontvangers';
$Definition['Redirecting...'] = 'Omleiden...';
$Definition['Remember me on this computer'] = 'Mij onthouden op deze computer';
$Definition['Remove My Picture'] = 'Mijn foto verwijderen';
$Definition['Request a new password'] = 'Nieuw wachtwoord aanvragen';
$Definition['Roles'] = 'Rollen';

$Definition['Save'] = 'Opslaan';
$Definition['Save Draft'] = 'Concept opslaan';
$Definition['Save Preferences'] = 'Voorkeuren opslaan';
$Definition['Search'] = 'Zoeken';
$Definition['Select an image on your computer (2mb max)'] = 'Selecteer een afbeelding op uw computer (max. 2 MB)';
$Definition['Send %s a Message'] = 'Bericht verzenden aan %s';
$Definition['Send Message'] = 'Bericht verzenden';
$Definition['Sent To'] = 'Verzonden aan';
$Definition['Share'] = 'Delen';
$Definition['she'] = 'zij';
$Definition['Sign In'] = 'Inloggen';
$Definition['Sign In with Google'] = 'Aanmelden met Google';
$Definition['Sign In with OpenID'] = 'Aanmelden met OpenID';
$Definition['Sign In with Twitter'] = 'Aanmelden met Twitter';
$Definition['Sign Out'] = 'Afmelden';
$Definition['Sign Up'] = 'Registreren';
$Definition['Sink'] = 'Laten zakken';
$Definition['somebody'] = 'iemand';
$Definition['Start a New Conversation'] = 'Nieuw gesprek beginnen';
$Definition['Start a New Discussion'] = 'Nieuwe discussie beginnen';
$Definition['Start Conversation'] = 'Gesprek beginnen';
$Definition['Started by %1$s'] = 'Begonnen door %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'Bedankt!';
$Definition['Thumbnail'] = 'Miniatuur';
$Definition['Transport error: %s'] = 'Er is een onherstelbare fout opgetreden bij het verwerken van de aanvraag.<br />De server geeft de volgende reactie: %s';

$Definition['Unbookmark'] = 'Bladwijzer verwijderen';
$Definition['Upload'] = 'Uploaden';
$Definition['Username'] = 'Gebruikersnaam';

$Definition['ValidateBoolean'] = '%s is geen geldige booleaanse operator.';
$Definition['ValidateConnection'] = 'Met de door u opgegeven verbindingsparameters kan geen verbinding met de database worden geopend. De database geeft de volgende foutmelding: <code>%s</code>';
$Definition['ValidateDate'] = '%s is geen geldige datum.';
$Definition['ValidateDecimal'] = '%s is geen geldig decimaalteken.';
$Definition['ValidateEmail'] = '%s is blijkbaar niet geldig.';
$Definition['ValidateEnum'] = '%s is niet geldig.';
$Definition['ValidateInteger'] = '%s is geen geldig geheel getal.';
$Definition['ValidateLength'] = '%1$s is %2$s tekens te lang.';
$Definition['ValidateMatch'] = 'De velden %s komen niet overeen.';
$Definition['ValidateMinimumAge'] = 'Je moet minimaal 16 zijn.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'U moet minimaal een %s selecteren.';
$Definition['ValidateRegex'] = '%s heeft blijkbaar niet de juiste indeling.';
$Definition['ValidateRequired'] = '%s is vereist.';
$Definition['ValidateRequiredArray'] = 'U moet minimaal een %s selecteren.';
$Definition['ValidateTime'] = '%s is geen geldige tijd.';
$Definition['ValidateTimestamp'] = '%s is geen geldige tijdstempel.';
$Definition['ValidateUsername'] = 'Gebruikersnamen moeten uit 3 t/m 20 tekens bestaan (letters, cijfers of onderstrepingstekens).';
$Definition['ValidateVersion'] = 'Het veld %s is geen geldig versienummer. Zie de functie php version_compare() voor voorbeelden van geldige versienummers.';
$Definition['Visits'] = 'Bezoeken';

$Definition['wall'] = 'virtuele muur';
$Definition['Why do you want to join?'] = 'Waarom wilt u deelnemen?';
$Definition['Write a comment'] = 'Opmerking schrijven';
$Definition['Write Comment'] = 'Opmerking schrijven';
$Definition['Write something about yourself...'] = 'Schrijf iets over uzelf...';

$Definition['you'] = 'u';
$Definition['You'] = 'U';
$Definition['You already have an account here.'] = 'U hebt al een account hier.';
$Definition['You are connected as %s through %s.'] = 'U bent verbonden als %s via %s.';
$Definition['You do not have any conversations.'] = 'U hebt geen gesprekken.';
$Definition['You do not have any notifications yet.'] = 'U hebt nog geen meldingen.';
$Definition['your'] = 'uw';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Uw aanvraag wordt door een systeembeheerder bekeken. U krijgt per e-mail bericht of uw aanvraag is goedgekeurd.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Uw geregistreerde gebruikersnaam: <strong>%s</strong>';

