/*
 * @author Stéphane LaFlèche <stephane.l@vanillaforums.com>
 * @copyright 2009-2018 Vanilla Forums Inc.
 * @license Proprietary
 */

import { IKbNavigationItemNested } from "@knowledge/@types/api";

export const dummyNavData: IKbNavigationItemNested[] = [
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Example Category",
        parentID: -1,
        url: "https://dev.vanilla.localhost/kb/categories/1-example-root",
        children: [
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Test Article - All Formatting & Embeds",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                children: [
                    {
                        recordType: "knowledgeCategory",
                        sort: null,
                        recordID: 1,
                        name: "Article 1",
                        parentID: 9,
                        url: "/kb/articles/1-article-one",
                    },
                    {
                        recordType: "knowledgeCategory",
                        sort: null,
                        recordID: 1,
                        name: "Chipmunks",
                        parentID: 9,
                        url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                        children: [
                            {
                                recordType: "knowledgeCategory",
                                sort: null,
                                recordID: 1,
                                name: "Armadillos",
                                parentID: 9,
                                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                            },
                            {
                                recordType: "knowledgeCategory",
                                sort: null,
                                recordID: 1,
                                name: "CurrentPage",
                                parentID: 9,
                                url: "asfasdfasd",
                            },
                        ],
                    },
                ],
            },
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Armadillos",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
            },
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Chipmunks",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                children: [
                    {
                        recordType: "knowledgeCategory",
                        sort: null,
                        recordID: 1,
                        name: "Armadillos",
                        parentID: 9,
                        url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                    },
                    {
                        recordType: "knowledgeCategory",
                        sort: null,
                        recordID: 1,
                        name: "Chipmunks",
                        parentID: 9,
                        url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                        children: [
                            {
                                recordType: "knowledgeCategory",
                                sort: null,
                                recordID: 1,
                                name: "Armadillos",
                                parentID: 9,
                                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                            },
                            {
                                recordType: "knowledgeCategory",
                                sort: null,
                                recordID: 1,
                                name: "Chipmunks",
                                parentID: 9,
                                url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                                children: [
                                    {
                                        recordType: "knowledgeCategory",
                                        sort: null,
                                        recordID: 1,
                                        name: "Armadillos",
                                        parentID: 9,
                                        url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                                    },
                                    {
                                        recordType: "knowledgeCategory",
                                        sort: null,
                                        recordID: 1,
                                        name: "Chipmunks",
                                        parentID: 9,
                                        url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Pee Mart",
        parentID: 1,
        url: "https://dev.vanilla.localhost/kb/categories/2-pee-mart",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Predator Urine",
        parentID: 2,
        url: "https://dev.vanilla.localhost/kb/categories/3-predator-urine",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Coyote Urine",
        parentID: 3,
        url: "https://dev.vanilla.localhost/kb/categories/4-coyote-urine",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Fox Urine",
        parentID: 3,
        url: "https://dev.vanilla.localhost/kb/categories/5-fox-urine",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Bobcat Urine",
        parentID: 3,
        url: "https://dev.vanilla.localhost/kb/categories/6-bobcat-urine",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "P-Gel",
        parentID: 2,
        url: "https://dev.vanilla.localhost/kb/categories/7-p-gel",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "P-Cover Granules",
        parentID: 2,
        url: "https://dev.vanilla.localhost/kb/categories/8-p-cover-granules",
        children: [
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Armadillos",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
            },
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Chipmunks",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
            },
        ],
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Article 2",
        parentID: 2,
        url: "/kb/articles/2-article-two",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Armadillos",
        parentID: 9,
        url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Chipmunks",
        parentID: 9,
        url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Test 3",
        parentID: 2,
        url: "/kb/articles/3-article-three",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Mountain Lion",
        parentID: 8,
        url: "https://dev.vanilla.localhost/kb/categories/13-mountain-lion",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Bear",
        parentID: 8,
        url: "https://dev.vanilla.localhost/kb/categories/14-bear",
        children: [
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Armadillos",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
            },
            {
                recordType: "knowledgeCategory",
                sort: null,
                recordID: 1,
                name: "Chipmunks",
                parentID: 9,
                url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
            },
        ],
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "Wolf",
        parentID: 8,
        url: "https://dev.vanilla.localhost/kb/categories/15-wolf",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "P-Wicks",
        parentID: 12,
        url: "https://dev.vanilla.localhost/kb/categories/16-p-wicks",
    },
    {
        recordType: "knowledgeCategory",
        sort: null,
        recordID: 1,
        name: "P-Dispensers",
        parentID: 12,
        url: "https://dev.vanilla.localhost/kb/categories/17-p-dispensers",
    },
];
