/*
 * @author Stéphane LaFlèche <stephane.l@vanillaforums.com>
 * @copyright 2009-2018 Vanilla Forums Inc.
 * @license GPL-2.0-only
 */

import { KbCategoryDisplayType } from "@knowledge/@types/api";

export const dummyNavData: any = {
    name: "Example Root",
    children: [
        {
            knowledgeCategoryID: 1,
            name: "Example Category",
            parentID: -1,
            isSection: true,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/1-example-root",
            children: [
                {
                    knowledgeCategoryID: 10,
                    name: "Armadillos",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                },
                {
                    knowledgeCategoryID: 11,
                    name: "Chipmunks",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                    children: [
                        {
                            knowledgeCategoryID: 10,
                            name: "Armadillos",
                            parentID: 9,
                            isSection: false,
                            displayType: KbCategoryDisplayType.GUIDE,
                            url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                        },
                        {
                            knowledgeCategoryID: 11,
                            name: "Chipmunks",
                            parentID: 9,
                            isSection: false,
                            displayType: KbCategoryDisplayType.GUIDE,
                            url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                        },
                    ],
                },
            ],
        },
        {
            knowledgeCategoryID: 2,
            name: "Pee Mart",
            parentID: 1,
            isSection: true,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/2-pee-mart",
        },
        {
            knowledgeCategoryID: 3,
            name: "Predator Urine",
            parentID: 2,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/3-predator-urine",
        },
        {
            knowledgeCategoryID: 4,
            name: "Coyote Urine",
            parentID: 3,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/4-coyote-urine",
        },
        {
            knowledgeCategoryID: 5,
            name: "Fox Urine",
            parentID: 3,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/5-fox-urine",
        },
        {
            knowledgeCategoryID: 6,
            name: "Bobcat Urine",
            parentID: 3,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/6-bobcat-urine",
        },
        {
            knowledgeCategoryID: 7,
            name: "P-Gel",
            parentID: 2,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/7-p-gel",
        },
        {
            knowledgeCategoryID: 8,
            name: "P-Cover Granules",
            parentID: 2,
            isSection: true,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/8-p-cover-granules",
            children: [
                {
                    knowledgeCategoryID: 10,
                    name: "Armadillos",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                },
                {
                    knowledgeCategoryID: 11,
                    name: "Chipmunks",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                },
            ],
        },
        {
            knowledgeCategoryID: 9,
            name: "Prey Animals",
            parentID: 2,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/9-prey-animals",
        },
        {
            knowledgeCategoryID: 10,
            name: "Armadillos",
            parentID: 9,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
        },
        {
            knowledgeCategoryID: 11,
            name: "Chipmunks",
            parentID: 9,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
        },
        {
            knowledgeCategoryID: 12,
            name: "Dispensers",
            parentID: 2,
            isSection: true,
            displayType: KbCategoryDisplayType.SEARCH,
            url: "https://dev.vanilla.localhost/kb/categories/12-dispensers",
        },
        {
            knowledgeCategoryID: 13,
            name: "Mountain Lion",
            parentID: 8,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/13-mountain-lion",
        },
        {
            knowledgeCategoryID: 14,
            name: "Bear",
            parentID: 8,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/14-bear",
            children: [
                {
                    knowledgeCategoryID: 10,
                    name: "Armadillos",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/10-armadillos",
                },
                {
                    knowledgeCategoryID: 11,
                    name: "Chipmunks",
                    parentID: 9,
                    isSection: false,
                    displayType: KbCategoryDisplayType.GUIDE,
                    url: "https://dev.vanilla.localhost/kb/categories/11-chipmunks",
                },
            ],
        },
        {
            knowledgeCategoryID: 15,
            name: "Wolf",
            parentID: 8,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/15-wolf",
        },
        {
            knowledgeCategoryID: 16,
            name: "P-Wicks",
            parentID: 12,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/16-p-wicks",
        },
        {
            knowledgeCategoryID: 17,
            name: "P-Dispensers",
            parentID: 12,
            isSection: false,
            displayType: KbCategoryDisplayType.GUIDE,
            url: "https://dev.vanilla.localhost/kb/categories/17-p-dispensers",
        },
    ],
};
