#!/bin/sh
# Changes the existing symlinks in a subdomain from source to stage, or vice versa
# This script assumes 2 arguments are passed: the name of the subdomain to create, and source or stage (whichever you want to symlink to).

# Variables
PATH=/srv/www/subdomains/${1}/
SOURCE=/srv/www/vanilla_${2}/
	
echo "Updating symlinks for: ${PATH} to ${SOURCE}"

   # Delete all existing symlinks first
   /bin/unlink "${PATH}applications/conversations"
   /bin/unlink "${PATH}applications/garden"
   /bin/unlink "${PATH}applications/vanilla"
   /bin/unlink "${PATH}plugins/VanillaInThisDiscussion"
   /bin/unlink "${PATH}plugins/HtmlPurifier"
   /bin/unlink "${PATH}plugins/googleadsense"
   /bin/unlink "${PATH}themes/default"
   /bin/unlink "${PATH}themes/vanillaforumscom"
   /bin/unlink "${PATH}conf/config-defaults.php"                                                                                                                 
   /bin/unlink "${PATH}conf/constants.php"
   /bin/unlink "${PATH}conf/locale.php"                                                                                                                             
   /bin/unlink "${PATH}js"                                                                                                                                                             		
   /bin/unlink "${PATH}library"
   /bin/unlink "${PATH}.htaccess"
   /bin/unlink "${PATH}bootstrap.php"

    # Now relink to the new place
    /bin/ln -s "${SOURCE}applications/conversations" "${PATH}applications/conversations"
    /bin/ln -s "${SOURCE}applications/garden" "${PATH}applications/garden"
    /bin/ln -s "${SOURCE}applications/vanilla" "${PATH}applications/vanilla"
    /bin/ln -s "${SOURCE}plugins/VanillaInThisDiscussion" "${PATH}plugins/VanillaInThisDiscussion"
    /bin/ln -s "${SOURCE}plugins/HtmlPurifier" "${PATH}plugins/HtmlPurifier"
    /bin/ln -s "${SOURCE}plugins/googleadsense" "${PATH}plugins/googleadsense"
    /bin/ln -s "${SOURCE}themes/vanillaforumscom" "${PATH}themes/default"
    /bin/ln -s "${SOURCE}themes/vanillaforumscom" "${PATH}themes/vanillaforumscom"
    /bin/ln -s "${SOURCE}conf/config-defaults.php" "${PATH}conf/config-defaults.php"                                                                                                                 
    /bin/ln -s "${SOURCE}conf/constants.php" "${PATH}conf/constants.php"
    /bin/ln -s "${SOURCE}conf/locale.php" "${PATH}conf/locale.php"                                                                                                                             
    /bin/ln -s "${SOURCE}js" "${PATH}js"                                                                                                                                                             		
    /bin/ln -s "${SOURCE}library" "${PATH}library"
    /bin/ln -s "${SOURCE}.htaccess" "${PATH}.htaccess"
    /bin/ln -s "${SOURCE}bootstrap.php" "${PATH}bootstrap.php"
    
    # Need to copy the index.php file because it defines the PATH_ROOT and the symbolic link will treat it as though it were in ${SOURCE}
    /bin/cp "${SOURCE}index.php" "${PATH}index.php"    
fi

exit