#!/bin/sh
# Generates a new forum structure in /srv/www/vhosts/
# This script assumes 1 argument is passed: the name of the vhost to create.

# Variables
PATH=/srv/www/vhosts/${1}/
SOURCE=/srv/www/vanilla_source/
PLUGINS=/srv/www/misc/plugins/
THEMES=/srv/www/misc/themes/
UTILS=/srv/www/misc/utils/
   
echo "Creating new vhost: ${PATH}"

# Don't do anything if the directory already exists
if [ ! -d "$PATH" ]; then

    # Create the new subdomain folder
    /bin/mkdir $PATH
    
    # Create subfolders
    /bin/mkdir ${PATH}applications
    /bin/mkdir ${PATH}cache
    /bin/mkdir ${PATH}cache/Smarty
    /bin/mkdir ${PATH}cache/Smarty/cache
    /bin/mkdir ${PATH}cache/Smarty/compile
    /bin/mkdir ${PATH}cache/HtmlPurifier
    /bin/mkdir ${PATH}conf
    /bin/mkdir ${PATH}plugins
    /bin/mkdir ${PATH}themes
    /bin/mkdir ${PATH}uploads
    
    # Fill it out the symbolic links to the vanilla source code
    
    #Applications
    /bin/ln -s "${SOURCE}applications/conversations" "${PATH}applications/conversations"
    /bin/ln -s "${SOURCE}applications/garden" "${PATH}applications/garden"
    /bin/ln -s "${SOURCE}applications/vanilla" "${PATH}applications/vanilla"
    #End Applications
    
    # Core Package Plugins
    /bin/ln -s "${SOURCE}plugins/VanillaInThisDiscussion" "${PATH}plugins/VanillaInThisDiscussion"
    /bin/ln -s "${SOURCE}plugins/HtmlPurifier" "${PATH}plugins/HtmlPurifier"
    # End Core Package Plugins
    
    # Custom VF.com Plugins
    /bin/ln -s "${PLUGINS}GettingStarted" "${PATH}plugins/GettingStarted"
    /bin/ln -s "${PLUGINS}googleadsense" "${PATH}plugins/googleadsense"
    /bin/ln -s "${PLUGINS}vfoptions" "${PATH}plugins/vfoptions"
    /bin/ln -s "${PLUGINS}CustomCSS" "${PATH}plugins/CustomCSS"
    # End Custom VF.com Plugins

    # Themes
    /bin/ln -s "${THEMES}vfcom" "${PATH}themes/default"
    /bin/ln -s "${THEMES}vfcom" "${PATH}themes/vfcom"
    # End Themes
        
    # Misc Symlinks
    /bin/ln -s "${SOURCE}conf/bootstrap.before.php" "${PATH}conf/bootstrap.before.php"
    /bin/ln -s "${SOURCE}conf/config-defaults.php" "${PATH}conf/config-defaults.php"
    /bin/ln -s "${SOURCE}conf/constants.php" "${PATH}conf/constants.php"
    /bin/ln -s "${SOURCE}conf/locale.php" "${PATH}conf/locale.php"
    /bin/ln -s "${SOURCE}js" "${PATH}js"
    /bin/ln -s "${SOURCE}library" "${PATH}library"
    /bin/ln -s "${UTILS}.htaccess" "${PATH}.htaccess"
    /bin/ln -s "${SOURCE}bootstrap.php" "${PATH}bootstrap.php"
    # End Misc
    
    # Need to copy the index.php file because it defines the PATH_ROOT and the symbolic link will treat it as though it were in ${SOURCE}
    /bin/cp "${SOURCE}index.php" "${PATH}index.php"
    
    # Create a new config file
    /usr/bin/touch ${PATH}conf/config.php
    
fi

exit