#!/bin/bash

PATH=/srv/www/subdomains/

for DIR in `/bin/ls /srv/www/subdomains`
do

echo $DIR
   # Remove existing symlinks
   /bin/rm ${PATH}${DIR}/plugins/GettingStarted
   /bin/rm ${PATH}${DIR}/plugins/googleadsense
   /bin/rm ${PATH}${DIR}/plugins/vfoptions
   /bin/rm ${PATH}${DIR}/plugins/downtime
   /bin/rm ${PATH}${DIR}/themes/vanillaforumscom
   /bin/rm ${PATH}${DIR}/themes/vfcom
   /bin/rm ${PATH}${DIR}/themes/default
   /bin/rm ${PATH}${DIR}/plugins/vfcom
   /bin/rm ${PATH}${DIR}/plugins/default
   
   # Add new symlinks
   /bin/ln -s /srv/www/misc/plugins/GettingStarted ${PATH}${DIR}/plugins/GettingStarted
   /bin/ln -s /srv/www/misc/plugins/googleadsense ${PATH}${DIR}/plugins/googleadsense
   /bin/ln -s /srv/www/misc/plugins/vfoptions ${PATH}${DIR}/plugins/vfoptions
   /bin/ln -s /srv/www/misc/themes/vfcom ${PATH}${DIR}/themes/vfcom
   /bin/ln -s /srv/www/misc/themes/vfcom ${PATH}${DIR}/themes/default

done