#!/bin/bash

PATH=/srv/www/vhosts/

for DIR in `/bin/ls /srv/www/vhosts`
do

echo $DIR
   # Remove existing symlink
   /bin/rm ${PATH}${DIR}/plugins/CustomCSS
   
   # Add new symlink
   /bin/ln -s /srv/www/misc/plugins/CustomCSS ${PATH}${DIR}/plugins/CustomCSS

done