<?php return array (
  'name' => 'Riceballs',
  'description' => 'A uniquely cute set of emoticons by David Lanham. Check out <a href="http://dlanham.com">dlanham.com</a> for more of his stuff.',
  'format' => '<img class="emoji" src="{src}" title="{name}" alt="{name}" srcset="{dir}/{basename}@2x{ext} 2x" />',
  'emoji' =>
  array (
    -1 => '-1.png',
    '+1' => '+1.png',
    'angry' => 'angry.png',
    'blush' => 'blush.png',
    'chuffed' => 'chuffed.png',
    'crazy' => 'crazy.png',
    'cry' => 'cry.png',
    'dizzy' => 'dizzy.png',
    'eh' => 'eh.png',
    'fearful' => 'fearful.png',
    'frown' => 'frown.png',
    'glasses' => 'glasses.png',
    'innocent' => 'innocent.png',
    'kiss' => 'kiss.png',
    'lol' => 'lol.png',
    'love' => 'love.png',
    'money' => 'money.png',
    'naughty' => 'naughty.png',
    'neutral' => 'neutral.png',
    'ohnoes' => 'ohnoes.png',
    'pirate' => 'pirate.png',
    'rage' => 'rage.png',
    'sarcastic' => 'sarcastic.png',
    'scream' => 'scream.png',
    'sick' => 'sick.png',
    'silenced' => 'silenced.png',
    'smile' => 'smile.png',
    'sunglasses' => 'sunglasses.png',
    'sweat' => 'sweat.png',
    'tongue' => 'tongue.png',
    'unamused' => 'unamused.png',
    'wink' => 'wink.png',
    'yum' => 'yum.png',
  ),
  'aliases' =>
  array (
    ':)' => 'smile',
    ':(' => 'frown',
    ';)' => 'wink',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    ':|' => 'neutral',
    'B)' => 'sunglasses',
    'o:)' => 'innocent',
    'o.O' => 'eh',
    '8-)' => 'glasses',
    '>_<' => 'rage',
  ),
  'editor' =>
  array (
    ':)' => 'smile',
    ':(' => 'frown',
    ';)' => 'wink',
    ':p' => 'tongue',
    ':\'(' => 'cry',
    ':|' => 'neutral',
    '8-)' => 'glasses',
    '>_<' => 'rage',
  ),
  'minSize' =>
  array (
    'w' => 18,
    'h' => 18,
  ),
  'maxSize' =>
  array (
    'w' => 30,
    'h' => 19,
  ),
  'sizes' =>
  array (
    0 => 1,
    1 => 2,
  ),
);
