<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:58 **/


$Definition['%1$s on %2$s'] = '%1$s op %2$s';
$Definition['%1$s Version %2$s'] = '%1$s versie %2$s';
$Definition['%s user(s) found.'] = '%s gebruiker(s) gevonden.';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '1 maand na verzending';
$Definition['1 week after being sent'] = '1 week na verzending';

$Definition['2 weeks after being sent'] = '2 weken na verzending';

$Definition['<General Error>'] = '<Algemene fout>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Registreren is GRATIS en gemakkelijk. Na registratie komt u hier terug en voert u de volgende instellingen in:'] = '<strong>Voor het gewone registratieformulier is het noodzakelijk</strong> dat nieuwe gebruikers tekst overnemen uit een Captcha-afbeelding om spammers buiten de site te houden. U hebt een account nodig bij <a href="http://recaptcha.net/">recaptcha.net</a>. Registreren is GRATIS en gemakkelijk. Na registratie komt u hier terug en voert u de volgende instellingen in:';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Lidmaatschap goedgekeurd';

$Definition['_Locale'] = 'Landinstelling';

$Definition['A url-friendly version of the category name for better SEO.'] = 'Een URL-vriendelijke versie van de categorienaam voor een betere optimalisatie voor zoekmachines.';
$Definition['Action'] = 'Actie';
$Definition['Activate'] = 'Activeren';
$Definition['Add'] = 'Toevoegen';
$Definition['Add Message'] = 'Bericht toevoegen';
$Definition['Add Route'] = 'Route toevoegen';
$Definition['Add User'] = 'Gebruiker toevoegen';
$Definition['Addons'] = 'Invoegtoepassingen';
$Definition['Administrator'] = 'Beheerder';
$Definition['Advanced'] = 'Geavanceerd';
$Definition['Advanced Forum Settings'] = 'Geavanceerde foruminstellingen';
$Definition['All <span>16</span>'] = 'Alle <span>16</span>';
$Definition['All <span>2</span>'] = 'Alle <span>2</span>';
$Definition['Announce'] = 'Aankondigen';
$Definition['Appearance'] = 'Vormgeving';
$Definition['Applicant'] = 'Aanvrager';
$Definition['Applicants'] = 'Aanvragers';
$Definition['Application'] = 'Applicatie';
$Definition['Application ID'] = 'Applicatie-id';
$Definition['Application Secret'] = 'Applicatiegeheim';
$Definition['ApplicationHelp'] = 'Applicaties maken het mogelijk om veel functionaliteit aan uw site toe te voegen.<br />Een applicatie die is toegevoegd aan uw map %s, kunt u hier in- en uitschakelen.';
$Definition['Applications'] = 'Applicaties';
$Definition['Approve'] = 'Goedkeuren';
$Definition['Archive Discussions'] = 'Discussies archiveren';
$Definition['Are you sure you want to do that?'] = 'Weet u zeker dat u dit wilt doen?';
$Definition['at'] = 'om';
$Definition['Authentication'] = 'Verificatie';

$Definition['Banned'] = 'Geband';
$Definition['Banner'] = 'Banner';
$Definition['Banner Logo'] = 'Bannerlogo';
$Definition['Banner Title'] = 'Bannertitel';

$Definition['Cancel'] = 'Annuleren';
$Definition['Capture locale pack changes.'] = 'Registreer de wijzigingen tussen een van uw pakketten met landinstellingen en de Locale Developer. De wijzigingen worden opgeslagen in het bestand <code>changes.php</code>.';
$Definition['Categories'] = 'Categorie‘n';
$Definition['Categories are used to help organize discussions. '] = 'Categorie‘n worden gebruikt om discussies in te delen. ';
$Definition['Category'] = 'Categorie';
$Definition['Category Url:'] = 'Categorie-URL:';
$Definition['Change the way that new users register with the site.'] = 'Wijzig de manier waarop nieuwe gebruikers zich registreren voor de site.';
$Definition['Check all permissions that apply for each role'] = 'Controleer alle rechten die van toepassing zijn op elke rol';
$Definition['Check all roles that apply to this user:'] = 'Controleer alle rollen die van toepassing zijn op deze gebruiker:';
$Definition['Choose a locale pack'] = 'Kies een pakket met landinstellingen';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Kies en configureer het verificatieschema van uw forum.';
$Definition['Choose who can send out invitations to new members:'] = 'Bepaal wie uitnodigingen kan sturen aan nieuwe leden:';
$Definition['Close'] = 'Sluiten';
$Definition['comment(s)'] = 'opmerking(en)';
$Definition['Comments'] = 'Opmerkingen';
$Definition['Comments per Page'] = 'Opmerkingen per pagina';
$Definition['Configure an Authenticator'] = 'Verificator configureren';
$Definition['Confirm'] = 'Bevestigen';
$Definition['Confirm Email'] = 'E-mailadres bevestigen';
$Definition['Consumer Key'] = 'Consumentensleutel';
$Definition['Consumer Secret'] = 'Consumentengeheim';
$Definition['Conversation Messages'] = 'Berichten van gesprek';
$Definition['Conversations'] = 'Gesprekken';
$Definition['Copy'] = 'Kopi‘ren';
$Definition['Copy locale pack.'] = 'Kopieer de definities van een pakket met landinstellingen naar de Locale Developer. De definities worden opgeslagen in het bestand <code>copied.php</code>.';
$Definition['Current Authenticator'] = 'Huidige verificator';
$Definition['Current Theme'] = 'Huidig thema';
$Definition['Customize your Public Profile'] = 'Openbaar profiel aanpassen';

$Definition['Dashboard'] = 'Dashboard';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Decline'] = 'Weigeren';
$Definition['Delete'] = 'Verwijderen';
$Definition['Description'] = 'Beschrijving';
$Definition['Disable'] = 'Uitschakelen';
$Definition['Disable Google Sign In'] = 'Google Sign In uitschakelen';
$Definition['Disable OpenID'] = 'OpenID uitschakelen';
$Definition['Disabled <span>0</span>'] = '<span>0</span> uitgeschakeld';
$Definition['Disabled <span>10</span>'] = '<span>10</span> uitgeschakeld';
$Definition['Disabled <span>11</span>'] = '<span>11</span> uitgeschakeld';
$Definition['Disabled <span>12</span>'] = '<span>12</span> uitgeschakeld';
$Definition['Disabled <span>9</span>'] = '<span>9</span> uitgeschakeld';
$Definition['Discussion & Comment Editing'] = 'Discussie en opmerking bewerken';
$Definition['discussion(s)'] = 'discussie(s)';
$Definition['Discussions'] = 'Discussies';
$Definition['Discussions per Page'] = 'Discussies per pagina';
$Definition['dot'] = 'dot';

$Definition['Edit'] = 'Bewerken';
$Definition['edit'] = 'bewerken';
$Definition['Edit Category'] = 'Categorie bewerken';
$Definition['Edit User'] = 'Gebruiker bewerken';
$Definition['EditContentTimeout.Notes'] = 'Opmerking: Als een gebruiker een rol heeft met rechten om inhoud te bewerken, dan hebben die rechten voorrang op alle hier geselecteerde waarden.';
$Definition['Email'] = 'E-mail';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'E-mail die vanuit de applicatie wordt verzonden, wordt geadresseerd op basis van deze naam en dit adres';
$Definition['Email visible to other users'] = 'E-mail zichtbaar voor andere gebruikers';
$Definition['EmailMembershipApproved'] = 'Beste %1$s,

Uw lidmaatschap is goedgekeurd. Meld u nu aan via deze koppeling:

  %2$s
  
Bedankt!';
$Definition['Enable'] = 'Inschakelen';
$Definition['Enable Google Sign In'] = 'Google Sign In inschakelen';
$Definition['Enable OpenID'] = 'OpenID inschakelen';
$Definition['Enabled <span>2</span>'] = '<span>2</span> ingeschakeld';
$Definition['Enabled <span>4</span>'] = '<span>4</span> ingeschakeld';
$Definition['Enabled <span>5</span>'] = '<span>5</span> ingeschakeld';
$Definition['Enabled <span>6</span>'] = '<span>6</span> ingeschakeld';
$Definition['Enabled <span>7</span>'] = '<span>7</span> ingeschakeld';
$Definition['Existing members send invitations to new members.'] = 'Bestaande leden kunnen uitnodigingen sturen aan nieuwe leden.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Met Facebook Connect kunnen gebruikers zich aanmelden via hun Facebook-account. <b>Deze invoegtoepassing werkt alleen wanneer u uw applicatie bij Facebook registreert.</b>';
$Definition['Facebook Settings'] = 'Facebook-instellingen';
$Definition['First Visit'] = 'Eerste bezoek';
$Definition['For more help on localization check out the page <a href="%s">hier</a>.'] = 'Bekijk <a href="%s">deze pagina</a> voor meer informatie over lokaliseren.';
$Definition['Forum Settings'] = 'Foruminstellingen';

$Definition['Garden.Email.SupportAddress'] = 'E-mail ondersteuning';
$Definition['Garden.Import.Description'] = 'Gebruik deze pagina om gegevens van een forum te importeren die met de Vanilla-exportfunctie zijn ge‘xporteerd. <a href="%s">Zie de documentatie over importeren.</a>';
$Definition['Garden.Import.InputInstructions'] = 'Voer het e-mailadres en wachtwoord in van de systeembeheerder van de gegevens die u wilt importeren.';
$Definition['Garden.Import.Overwrite.Description'] = 'Waarschuwing: Alle gegevens in dit forum worden overschreven.';
$Definition['Generate'] = 'Genereren';
$Definition['Generate Password'] = 'Wachtwoord genereren';
$Definition['Go'] = 'OK';
$Definition['Google Sign In Settings'] = 'Instellingen Google Sign In';
$Definition['Guest'] = 'Gast';

$Definition['here'] = 'hier';

$Definition['Import'] = 'Importeren';
$Definition['Inbox'] = 'Postvak IN';
$Definition['Information'] = 'Informatie';
$Definition['Internal'] = 'Intern';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Wanneer u met registratie op uitnodiging werkt, krijgt de gebruiker op zijn of haar profielpagina een koppeling die <a href="%s" class="Popup">Mijn uitnodigingen</a> heet.';
$Definition['Invitations per month'] = 'Uitnodigingen per maand';
$Definition['Invitations will expire'] = 'Uitnodigingen verlopen';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'U doet er goed aan om het aantal tekens dat maximaal in een opmerking kan worden gebruikt, beperkt te houden.';

$Definition['Key Type'] = 'Type sleutel';
$Definition['Key Value'] = 'Waarde sleutel';

$Definition['Last Active'] = 'Laatste keer actief';
$Definition['Last Visit'] = 'Laatste bezoek';
$Definition['Locale Developer'] = 'Locale Developer';
$Definition['Locale Developer Settings %s.'] = 'Instellingen Locale Developer %s.';
$Definition['Locale info file settings.'] = '<p>Wanneer u het ZIP-bestand genereert, kunt u hieronder de gegevens voor de landinstellingen opgeven.</p> <p>U kunt het pakket met landinstellingen downloaden in een ZIP-bestand door <a href="%s">hier</a> te klikken.</p>';
$Definition['Locale Key (Folder)'] = 'Sleutel landinstellingen (map)';
$Definition['Locale Name'] = 'Naam landinstellingen';
$Definition['Locales'] = 'Landinstellingen';
$Definition['Locales are in your %s folder.'] = 'Met landinstellingen kunt u andere talen ondersteunen op uw site. Landinstellingen die zijn toegevoegd aan uw map %s, kunt u hier in- en uitschakelen.';
$Definition['Location'] = 'Locatie';

$Definition['Manage Applicants'] = 'Aanvragers beheren';
$Definition['Manage Applications'] = 'Applicaties beheren';
$Definition['Manage Categories'] = 'Categorie‘n beheren';
$Definition['Manage Messages'] = 'Berichten beheren';
$Definition['Manage Plugins'] = 'Invoegtoepassingen beheren';
$Definition['Manage Roles & Permissions'] = 'Rollen en rechten beheren';
$Definition['Manage Routes'] = 'Routes beheren';
$Definition['Manage Spam'] = 'Spam beheren';
$Definition['Manage Themes'] = "Thema's beheren";
$Definition['Manage Users'] = 'Gebruikers beheren';
$Definition['Manage your Plugins'] = 'Uw invoegtoepassingen beheren';
$Definition['Max Comment Length'] = 'Maximale lengte opmerkingen';
$Definition['Member'] = 'Lid';
$Definition['Message'] = 'Bericht';
$Definition['Messages'] = 'Berichten';
$Definition['Messages can appear anywhere in your application.'] = 'Berichten kunnen overal in uw applicatie worden weergegeven en kunnen worden gebruikt om uw gebruikers op de hoogte te brengen van nieuws en gebeurtenissen. Gebruik deze pagina om uw berichten anders in te delen (omhoog/omlaag slepen).';
$Definition['Method'] = 'Methode';
$Definition['minute(s)'] = 'minu(u)t(en)';
$Definition['Moderator'] = 'Moderator';

$Definition['Name'] = 'Naam';
$Definition['never'] = 'nooit';
$Definition['New comments in the last day'] = 'Nieuwe opmerkingen van de afgelopen dag';
$Definition['New comments in the last week'] = 'Nieuwe opmerkingen van de afgelopen week';
$Definition['New conversations in the last day'] = 'Nieuwe gesprekken van de afgelopen dag';
$Definition['New conversations in the last week'] = 'Nieuwe gesprekken van de afgelopen week';
$Definition['New discussions in the last day'] = 'Nieuwe discussies van de afgelopen dag';
$Definition['New discussions in the last week'] = 'Nieuwe discussies van de afgelopen week';
$Definition['New messages in the last day'] = 'Nieuwe berichten van de afgelopen dag';
$Definition['New messages in the last week'] = 'Nieuwe berichten van de afgelopen week';
$Definition['New Password'] = 'Nieuw wachtwoord';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'Nieuwe gebruikers worden gecontroleerd en goedgekeurd door de systeembeheerder (u dus).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'Nieuwe gebruikers vullen een eenvoudig formulier in en krijgen onmiddellijk toegang.';
$Definition['New users in the last day'] = 'Nieuwe gebruikers van de afgelopen dag';
$Definition['New users in the last week'] = 'Nieuwe gebruikers van de afgelopen week';
$Definition['None'] = 'Geen';
$Definition['Not Authorized (401)'] = 'Geen toestemming (401)';
$Definition['Not Found (404)'] = 'Niet gevonden (404)';

$Definition['OK'] = 'OK';
$Definition['Okay'] = 'OK';
$Definition['Only Allow Each User To Post'] = 'Maximaal aantal berichten per gebruiker';
$Definition['OpenID Settings'] = 'Instellingen OpenID';
$Definition['Options'] = 'Opties';
$Definition['Or Spamblock For'] = 'Of spam blokkeren gedurende';
$Definition['Organize your Categories'] = 'Categorie‘n indelen';
$Definition['Other Themes'] = "Andere thema's";
$Definition['Outgoing Email'] = 'Uitgaande e-mail';

$Definition['Page'] = 'Pagina';
$Definition['Panel Box'] = 'Panelbox';
$Definition['Password'] = 'Wachtwoord';
$Definition['Password Options'] = 'Wachtwoordopties';
$Definition['Permanent (301)'] = 'Permanent (301)';
$Definition['Please choose an authenticator to configure.'] = 'Kies een verificator om te configureren.';
$Definition['Plugin'] = 'Invoegtoepassing';
$Definition['PluginHelp'] = 'Invoegtoepassingen maken het mogelijk om grote groepen functionaliteit aan uw site toe te voegen.<br />Een invoegtoepassing die is toegevoegd aan uw map %s, kunt u hier in- en uitschakelen.';
$Definition['Plugins'] = 'Invoegtoepassingen';
$Definition['Position'] = 'Positie';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Voorkom spam op uw forum door het aantal discussies te beperken &amp; comments that users can post within a given period of time.';
$Definition['Private Key'] = 'Private sleutel';
$Definition['Public Key'] = 'Openbare sleutel';

$Definition['Recently Active Users'] = 'Onlangs actieve gebruikers';
$Definition['Refresh Comments'] = 'Opmerkingen vernieuwen';
$Definition['Registration'] = 'Registratie';
$Definition['Remove'] = 'Verwijderen';
$Definition['Remove locale developer files.'] = 'Verwijder uw Locale Developer-bestanden en reset uw wijzigingen.';
$Definition['Requires: '] = 'Vereist: ';
$Definition['Reset Password'] = 'Wachtwoord resetten';
$Definition['Reset password and send email notification to user'] = 'Wachtwoord resetten en e-mailbericht sturen aan gebruiker';
$Definition['Reveal Password'] = 'Wachtwoord bekendmaken';
$Definition['Role'] = 'Rol';
$Definition['Roles & Permissions'] = 'Rollen en rechten';
$Definition['Roles determine user\'s permissions.'] = 'Elke gebruiker van uw site krijgt minstens ŽŽn rol toegewezen. Rollen bepalen wat de gebruikers mogen doen.';
$Definition['Route'] = 'Route';
$Definition['Route Expression'] = 'Route-expressie';
$Definition['Routes'] = 'Routes';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Routes kunnen worden gebruikt om gebruikers naar bepaalde delen van uw site te sturen, afhankelijk van de URL.';

$Definition['Save'] = 'Opslaan';
$Definition['Search'] = 'Zoeken';
$Definition['seconds'] = 'seconden';
$Definition['Select the file to import'] = 'Bestand selecteren om te importeren';
$Definition['Settings'] = 'Instellingen';
$Definition['Sign Out'] = 'Afmelden';
$Definition['Sink'] = 'Laten zakken';
$Definition['SMTP Host'] = 'SMTP-host';
$Definition['SMTP Password'] = 'SMTP-wachtwoord';
$Definition['SMTP Port'] = 'SMTP-poort';
$Definition['SMTP Security'] = 'SMTP-beveiliging';
$Definition['SMTP User'] = 'SMTP-gebruiker';
$Definition['Spam'] = 'Spam';
$Definition['Start your First Discussion'] = 'Begin uw eerste discussie';

$Definition['Target'] = 'Doel';
$Definition['Temporary (302)'] = 'Tijdelijk (302)';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'De verificator %s heeft geen speciale configuratieopties.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'De invoegtoepassing kan niet worden ingeschakeld, want er is een onherstelbare fout opgetreden: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'Het bannerlogo staat bovenaan uw forum.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = "De bannertitel staat in de linkerbovenhoek van elke pagina. Als een bannerlogo wordt verzonden, komt dit in de plaats van de bannertitel op de forumpagina's die de gebruiker te zien krijgt.";
$Definition['The file failed to upload.'] = 'Het bestand kan niet worden verzonden.';
$Definition['ThemeHelp'] = 'Met een thema kunt u de vormgeving aanpassen &amp; feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Themes'] = "Thema's";
$Definition['There are currently no applicants.'] = 'Er zijn geen aanvragen.';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'Met deze invoegtoepassing kunnen gebruikers zich aanmelden met OpenID. <b>Klik op Instellingen nadat u de invoegtoepassing hebt ingeschakeld om aanmelding via OpenID in te schakelen</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'Met deze invoegtoepassing kunnen gebruikers zich aanmelden met hun Google-account. <b>Klik op Instellingen nadat u de invoegtoepassing hebt ingeschakeld om aanmelding via Google Sign In in te schakelen</b>.';
$Definition['This plugin helps locale package development.'] = 'Deze invoegtoepassing helpt bij het ontwikkelen van landinstellingen. Hier bewaart de invoegtoepassing een werkend pakket landinstellingen: <code>%s</code>.';
$Definition['Tools'] = 'Tools';
$Definition['Transport error: %s'] = 'Er is een onherstelbare fout opgetreden bij het verwerken van de aanvraag.<br />De server geeft de volgende reactie: %s';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Met Twitter Connect kunnen gebruikers zich aanmelden via hun Twitter-account. <b>Deze invoegtoepassing werkt alleen wanneer u uw applicatie bij Twitter registreert.</b>';
$Definition['Twitter Settings'] = 'Instellingen Twitter';
$Definition['Type'] = 'Type';

$Definition['Unlimited'] = 'Onbeperkt';
$Definition['Upload'] = 'Uploaden';
$Definition['Url'] = 'URL';
$Definition['User'] = 'Gebruiker';
$Definition['User Registration Settings'] = 'Instellingen gebruikersregistratie';
$Definition['Username'] = 'Gebruikersnaam';
$Definition['Users'] = 'Gebruikers';

$Definition['ValidateRequired'] = '%s is vereist.';
$Definition['Vanilla.Archive.Description'] = 'U kunt forumdiscussies van v——r een bepaalde datum laten archiveren. Gearchiveerde discussies worden gesloten. Nieuwe berichten zijn niet meer mogelijk.';
$Definition['Version'] = 'Versie';
$Definition['Version %s'] = 'Versie %s';
$Definition['version %s'] = 'versie %s';
$Definition['View'] = 'Weergeven';
$Definition['Visit Site'] = 'Site bezoeken';

$Definition['Warning'] = 'Waarschuwing';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'Standaard proberen we de lokale e-mailserver te gebruiken voor het verzenden van e-mail. Als u een aparte SMTP-e-mailserver wilt gebruiken, kunt u die hieronder configureren.';
$Definition['Welcome Aboard!'] = 'Welkom!';
$Definition['What\'s the Buzz?'] = 'Wat hebben we hier?';
$Definition['Within'] = 'Binnen';

$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'Als u ooit niet meer in uw eigen forum kunt, dan is aanmelden altijd nog mogelijk met uw oorspronkelijke e-mailbericht en wachtwoord van Vanilla op <a href="%1$s">%1$s</a>';
$Definition['You can place files in your /uploads folder.'] = 'Als uw bestand te groot is om rechtstreeks naar deze pagina te uploaden, dan kunt u het bestand in de map /uploads zetten. De bestandsnaam moet beginnen met het woord <b>export</b> en eindigen met <b>.txt of .gz</b>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'U kunt de invoegtoepassing %1$s niet uitschakelen, want de invoegtoepassing %2$s heeft die nodig.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'U kunt de invoegtoepassing OpenID niet uitschakelen, want de invoegtoepassing Google Sign In heeft die nodig.';
$Definition['Your changes have been saved.'] = 'Uw wijzigingen zijn opgeslagen.';
$Definition['Your settings have been saved.'] = 'Uw instellingen zijn opgeslagen.';

